platform :ios, '12.0'

target 'MediasoupExample' do
#	use_frameworks!
	#pod 'Mediasoup-Client-Swift', :path => '../'
pod 'Mediasoup-Client-Swift', :git => "https://github.com/iamqk/mediasoup-client-swift", :tag => '0.1.3.1'

end
